#!/bin/bash

mvn archetype:generate \
    -DgroupId=com.dosomedev \
    -DartifactId=treemap-app \
    -DarchetypeArtifactId=maven-archetype-quickstart \
    -DarchetypeVersion=1.4 \
    -DinteractiveMode=false
