#!/bin/bash

mvn archetype:generate \
    -DgroupId=com.dosomedev \
    -DartifactId=arraylist-app \
    -DarchetypeArtifactId=maven-archetype-quickstart \
    -DarchetypeVersion=1.1 \
    -DinteractiveMode=false
